import { join } from 'path';

const outPath = join(import.meta.dir, '../src/generated-wasm.ts');

const content = `// Auto-generated by scripts/embed-wasm.ts
export const wasmBase64 = "";
`;

await Bun.write(outPath, content);
console.log('Skipped embedding WASM (using external file mode)');
