import { join } from 'path';

const wasmPath = join(import.meta.dir, '../dist/vsignal.wasm');
const outPath = join(import.meta.dir, '../src/generated-wasm.ts');

const file = Bun.file(wasmPath);
if (!await file.exists()) {
  console.error('WASM file not found at', wasmPath);
  process.exit(1);
}

const buffer = await file.arrayBuffer();
const base64 = Buffer.from(buffer).toString('base64');

const content = `// Auto-generated by scripts/embed-wasm.ts
export const wasmBase64 = "${base64}";
`;

await Bun.write(outPath, content);
console.log('Embedded WASM into', outPath);
